apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis-project
  namespace: argocd
spec:
  description: Project for Redis deployment via ArgoCD
  sourceRepos:
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: redis
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
