apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: redis-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 21.2.3
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: true
        master:
          persistence:
            enabled: true
            size: 8Gi
            storageClass: longhorn
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
